export const CANDIDATE_SOURCE_MAP = {
    'paper.title': ['paper.title'],
    'paper.doi': ['paper.doi'],
    'paper.abstract': ['paper.abstract'],
    'paper.summary': ['paper.abstract'],
    'paper.keywords': ['paper.keywordsText'],
    'paper.citationCount': ['paper.citationCount'],
    'paper.language': ['paper.language'],
    'paper.type': ['paper.type'],
    'paper.presentationType': ['paper.presentationType'],
    'paper.funding': ['paper.fundingText'],
    'paper.url': ['paper.url'],

    'author.names': ['authors.namesText'],
    'author.affiliations': ['authors.affiliations'],

    'publication.venue': ['publication.venue', 'publication.venueRaw'],
    'publication.venueShort': ['publication.venueShort'],
    'publication.year': ['publication.date.year'],
    'publication.date.full': ['publication.date.raw'],
    'publication.date.year': ['publication.date.year'],
    'publication.date.month': ['publication.date.month'],
    'publication.date.day': ['publication.date.day'],
    'publication.volume': ['publication.volume'],
    'publication.issue': ['publication.issue'],
    'publication.volumeIssue': ['publication.volumeIssue'],
    'publication.pages.range': ['publication.pages.range'],
    'publication.pages.first': ['publication.pages.first'],
    'publication.pages.last': ['publication.pages.last'],
    'publication.articleNumber': ['publication.articleNumber'],
    'publication.indexing': ['publication.indexing', 'publication.indexingText'],

    'conference.name': ['conference.name'],
    'conference.shortName': ['conference.shortName'],
    'conference.location': ['conference.location'],
    'conference.organizer': ['conference.organizersText'],
    'conference.date.full': ['conference.eventDate.raw'],
    'conference.date.year': ['conference.eventDate.year'],
    'conference.date.month': ['conference.eventDate.month'],
    'conference.date.day': ['conference.eventDate.day'],
    'conference.date.start.full': ['conference.start.raw'],
    'conference.date.start.year': ['conference.start.year'],
    'conference.date.start.month': ['conference.start.month'],
    'conference.date.start.day': ['conference.start.day'],
    'conference.date.end.full': ['conference.end.raw'],
    'conference.date.end.year': ['conference.end.year'],
    'conference.date.end.month': ['conference.end.month'],
    'conference.date.end.day': ['conference.end.day'],

    'narrative.summary': ['paper.abstract'],
    'narrative.description': ['paper.abstract'],
    'narrative.notes': ['paper.notesText']
};
